title: "Topological Defects"
author: "Fergus Baker"

execute:
  execute_notebooks: "off"

repository:
  url:  "https://github.com/dustpancake/topological-defects"
  branch: master


html:
  home_page_in_navbar : true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true


only_build_toc_files: true

latex:
  latex_engine: xelatex

bibtex_bibfiles:
  - "diff-geo/references.bib"

sphinx:
  config:
    html_css_files: 
      - "_static/mathematics.css"

