title: "Mathematics Reference"
author: "Fergus Baker"
logo: "logo.png"

execute:
  execute_notebooks: "off"

repository:
  url:  "https://github.com/fjebaker/maths-reference"
  branch: master


html:
  home_page_in_navbar : true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  navbar_number_sections: true
  extra_footer: |
    <div>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>.
    </div>


only_build_toc_files: true

latex:
  latex_engine: xelatex

bibtex_bibfiles:
  - "diff-geo/references.bib"

sphinx:
  config:
    html_css_files: 
      - "_static/mathematics.css"

